services:
  # Serviço do Backend (API FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - ainbox-net

  # Serviço do Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Impede que o node_modules local sobrescreva o do contêiner
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - ainbox-net

  # Serviço do Redis Local
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ainbox-net

networks:
  ainbox-net:
    driver: bridge

volumes:
  redis_data:
    driver: local
