steps:
  # Etapa 1: Constrói a imagem Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "southamerica-east1-docker.pkg.dev/${PROJECT_ID}/ainbox-images/ainbox-backend:${COMMIT_SHA}"
      - "."
    dir: "backend"

  # Etapa 2: Envia a imagem para o Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "southamerica-east1-docker.pkg.dev/${PROJECT_ID}/ainbox-images/ainbox-backend:${COMMIT_SHA}"

  # Etapa 3: Faz o deploy no Cloud Run com a configuração de ambiente CORRETA e UNIFICADA
  - name: "gcr.io/google-appengine/exec-wrapper"
    args:
      - "-i"
      - "gcr.io/cloud-builders/gcloud"
      - "--"
      - "run"
      - "deploy"
      - "ainbox-backend"
      - "--image"
      - "southamerica-east1-docker.pkg.dev/${PROJECT_ID}/ainbox-images/ainbox-backend:${COMMIT_SHA}"
      - "--region"
      - "southamerica-east1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory=1Gi"
      - "--cpu=1"
      - "--timeout=300"
      - "--concurrency=80"
      # Flag única com valores contendo caracteres especiais devidamente escapados
      - '--set-env-vars=APP_NAME="AInBox API",VERSION=1.0.0,ENVIRONMENT=production,DEBUG=false,HOST=0.0.0.0,ALLOWED_ORIGINS=*,GEMINI_MODEL=gemini-1.5-flash,WS_HEARTBEAT_INTERVAL=30,WS_MAX_CONNECTIONS=100,MAX_FILE_SIZE=5242880,MAX_TOTAL_SIZE=104857600,MAX_FILES_PER_REQUEST=20,MAX_STRINGS_PER_REQUEST=20,ALLOWED_FILE_TYPES=".txt,.pdf",RATE_LIMIT_PER_MINUTE=10,RATE_LIMIT_WINDOW=60,RATE_LIMIT_BURST=5,REDIS_HOST=10.53.247.67,REDIS_PORT=6379,REDIS_DB=0,REDIS_SSL=true,REDIS_TTL=60'

images:
  - "southamerica-east1-docker.pkg.dev/${PROJECT_ID}/ainbox-images/ainbox-backend:${COMMIT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY
