steps:
  # Etapa 1: Constrói a imagem Docker a partir do Dockerfile na pasta 'backend'
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "southamerica-east1-docker.pkg.dev/${PROJECT_ID}/ainbox-images/ainbox-backend:${COMMIT_SHA}"
      - "."
    dir: "backend"

  # Etapa 2: Envia a imagem para o Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "southamerica-east1-docker.pkg.dev/${PROJECT_ID}/ainbox-images/ainbox-backend:${COMMIT_SHA}"

  # Etapa 3: Faz o deploy da nova imagem no serviço existente do Cloud Run com todas as variáveis
  - name: "gcr.io/google-appengine/exec-wrapper"
    args:
      - "-i"
      - "gcr.io/cloud-builders/gcloud"
      - "--"
      - "run"
      - "deploy"
      - "ainbox-backend"
      - "--image"
      - "southamerica-east1-docker.pkg.dev/${PROJECT_ID}/ainbox-images/ainbox-backend:${COMMIT_SHA}"
      - "--region"
      - "southamerica-east1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory=1Gi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=10"
      - "--timeout=300"
      - "--concurrency=1000"
      # Configurações básicas da aplicação
      - "--set-env-vars=APP_NAME=AInBox API,VERSION=1.0.0,ENVIRONMENT=production,DEBUG=false,HOST=0.0.0.0"
      # Configurações de CORS e WebSocket
      - "--update-env-vars=ALLOWED_ORIGINS=*,GEMINI_MODEL=gemini-1.5-flash,WS_HEARTBEAT_INTERVAL=30,WS_MAX_CONNECTIONS=100"
      # Configurações de processamento de arquivos
      - "--update-env-vars=MAX_FILE_SIZE=5242880,MAX_TOTAL_SIZE=104857600,MAX_FILES_PER_REQUEST=20,MAX_STRINGS_PER_REQUEST=20,ALLOWED_FILE_TYPES=.txt%2C.pdf"
      # Configurações de rate limiting
      - "--update-env-vars=RATE_LIMIT_PER_MINUTE=10,RATE_LIMIT_WINDOW=60,RATE_LIMIT_BURST=5"
      # Configurações do Redis (valores padrão)
      - "--update-env-vars=REDIS_HOST=localhost,REDIS_PORT=6379,REDIS_DB=0,REDIS_SSL=false,REDIS_TTL=60"
      # Configurações de logging
      - "--update-env-vars=LOG_LEVEL=info"

images:
  - "southamerica-east1-docker.pkg.dev/${PROJECT_ID}/ainbox-images/ainbox-backend:${COMMIT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY
